application:
  host: "0.0.0.0"
  port: ":8000"
db:
  name: "wb"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  ssl_mode: "disable"
  dsn_template: "host=%s port=%s dbname=%s user=%s password=%s sslmode=%s"